In [86]:
import pandas as pd
from unidecode import unidecode

# Replace 'your_file_path' with the actual path where the file is located
file_path = "rookies_by_year (1).csv"

# Load the CSV file
data = pd.read_csv(file_path)

# Normalize player names in the dataset
data['Player'] = data['Player'].apply(lambda x: unidecode(x))

# Display the first few rows
data.head()

,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,3PA,...,FT%,PER GAME MP,PER GAME PTS,PER GAME TRB,PER GAME AST,PER GAME STL,PER GAME BLK,Player Reference,League,Season
0,Ibou Badji,202312260POR,21.0,1,17,199.0,12,19,0.0,0.0,...,0.5,11.7,1.7,2.8,0.8,0.1,1.2,badjiib01,NBA,2023-2024
1,Amari Bailey,202311120NYK,19.0,1,3,15.0,2,7,0.0,3.0,...,0.5,5.0,1.7,0.7,0.3,0.0,0.0,baileam01,NBA,2023-2024
2,Emoni Bates,202310280CLE,20.0,1,10,76.0,6,25,5.0,20.0,...,0.5,7.6,1.8,1.0,0.6,0.1,0.2,batesem01,NBA,2023-2024
3,Jules Bernard,202312080BRK,24.0,1,6,28.0,3,12,1.0,8.0,...,NaN,4.7,1.2,0.8,0.8,0.2,0.2,bernaju01,NBA,2023-2024
4,Onuralp Bitim,202311040DEN,24.0,1,2,6.0,0,2,0.0,1.0,...,NaN,3.0,0.0,0.0,0.0,0.0,0.0,bitimon01,NBA,2023-2024

Removing every entry before the NBA merger in 1976

In [87]:
# Ensure the 'Season' column is treated as numeric
data['Season'] = data['Season'].astype(str).str[:4].astype(int)

# Filter the dataset to include only the 1976-1977 season and beyond
data_filtered = data[data['Season'] >= 1976]

# Display the last five rows of the updated filtered DataFrame
data_filtered.tail()

,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,3PA,...,FT%,PER GAME MP,PER GAME PTS,PER GAME TRB,PER GAME AST,PER GAME STL,PER GAME BLK,Player Reference,League,Season
3571,Chuck Williams,197610220IND,30.0,1,65,867.0,78,210,NaN,NaN,...,0.782,13.3,3.4,1.6,2.0,0.5,0.0,willich02,NBA,1976
3572,Chuckie Williams,197612160CLE,23.0,1,22,65.0,14,47,NaN,NaN,...,0.750,3.0,1.7,0.2,0.3,0.0,0.0,willich03,NBA,1976
3573,John Williamson,197610220GSW,25.0,1,72,2481.0,618,1347,NaN,NaN,...,0.787,34.5,20.8,2.7,2.8,1.5,0.2,willijo01,NBA,1976
3574,Willie Wise,197610220IND,29.0,1,75,1403.0,237,513,NaN,NaN,...,0.651,18.7,8.2,3.4,1.9,0.8,0.2,wisewi01,NBA,1976
3575,Larry Wright,197610220WSB,22.0,1,78,1421.0,262,595,NaN,NaN,...,0.765,18.2,7.8,1.3,3.0,0.7,0.1,wrighla01,NBA,1976

Making TOV in to TOV per Game and removing unnecessary stats

In [88]:
# Update the list of columns to retain, accounting for exact column names
columns_to_keep = [
    "Player", "Age", "G", "MP", "FG%", "3P%", "FT%", 
    "PER GAME MP", "PER GAME  PTS", "PER GAME TRB", 
    "PER GAME AST", "PER GAME STL", "PER GAME BLK"
]

# Filter the dataset to retain the specified columns
filtered_dataset = data[columns_to_keep]

# Calculate PER GAME TOV (Turnovers Per Game)
filtered_dataset["PER GAME TOV"] = data["TOV"] / data["G"]


# Show a preview of the filtered dataset
filtered_dataset.head()

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_27912\608673421.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dataset["PER GAME TOV"] = data["TOV"] / data["G"]

,Player,Age,G,MP,FG%,3P%,FT%,PER GAME MP,PER GAME PTS,PER GAME TRB,PER GAME AST,PER GAME STL,PER GAME BLK,PER GAME TOV
0,Ibou Badji,21.0,17,199.0,0.632,NaN,0.5,11.7,1.7,2.8,0.8,0.1,1.2,0.823529
1,Amari Bailey,19.0,3,15.0,0.286,0.000,0.5,5.0,1.7,0.7,0.3,0.0,0.0,0.333333
2,Emoni Bates,20.0,10,76.0,0.240,0.250,0.5,7.6,1.8,1.0,0.6,0.1,0.2,0.100000
3,Jules Bernard,24.0,6,28.0,0.250,0.125,NaN,4.7,1.2,0.8,0.8,0.2,0.2,0.333333
4,Onuralp Bitim,24.0,2,6.0,0.000,0.000,NaN,3.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [89]:
# Round the PER GAME TOV column to 1 decimal place
filtered_dataset["PER GAME TOV"] = filtered_dataset["PER GAME TOV"].round(1)


# Show a preview of the updated dataset
filtered_dataset.head()

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_27912\2496087596.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dataset["PER GAME TOV"] = filtered_dataset["PER GAME TOV"].round(1)

,Player,Age,G,MP,FG%,3P%,FT%,PER GAME MP,PER GAME PTS,PER GAME TRB,PER GAME AST,PER GAME STL,PER GAME BLK,PER GAME TOV
0,Ibou Badji,21.0,17,199.0,0.632,NaN,0.5,11.7,1.7,2.8,0.8,0.1,1.2,0.8
1,Amari Bailey,19.0,3,15.0,0.286,0.000,0.5,5.0,1.7,0.7,0.3,0.0,0.0,0.3
2,Emoni Bates,20.0,10,76.0,0.240,0.250,0.5,7.6,1.8,1.0,0.6,0.1,0.2,0.1
3,Jules Bernard,24.0,6,28.0,0.250,0.125,NaN,4.7,1.2,0.8,0.8,0.2,0.2,0.3
4,Onuralp Bitim,24.0,2,6.0,0.000,0.000,NaN,3.0,0.0,0.0,0.0,0.0,0.0,0.0

Time to add the awards

NBA MVP

Season	Player
	
2023-24	Nikola Jokić
2022-23	Joel Embiid
2021-22	Nikola Jokić
2020-21	Nikola Jokić
2019-20	Giannis Antetokounmpo
2018-19	Giannis Antetokounmpo
2017-18	James Harden
2016-17	Russell Westbrook
2015-16	Stephen Curry
2014-15	Stephen Curry
2013-14	Kevin Durant
2012-13	LeBron James
2011-12	LeBron James
2010-11	Derrick Rose
2009-10	LeBron James
2008-09	LeBron James
2007-08	Kobe Bryant
2006-07	Dirk Nowitzki
2005-06	Steve Nash
2004-05	Steve Nash
2003-04	Kevin Garnett
2002-03	Tim Duncan
2001-02	Tim Duncan
2000-01	Allen Iverson
1999-00	Shaquille O'Neal
1998-99	Karl Malone
1997-98	Michael Jordan
1996-97	Karl Malone
1995-96	Michael Jordan
1994-95	David Robinson
1993-94	Hakeem Olajuwon
1992-93	Charles Barkley
1991-92	Michael Jordan
1990-91	Michael Jordan
1989-90	Magic Johnson
1988-89	Magic Johnson
1987-88	Michael Jordan
1986-87	Magic Johnson
1985-86	Larry Bird
1984-85	Larry Bird
1983-84	Larry Bird
1982-83	Moses Malone
1981-82	Moses Malone
1980-81	Julius Erving
1979-80	Kareem Abdul-Jabbar
1978-79	Moses Malone
1977-78	Bill Walton
1976-77	Kareem Abdul-Jabbar

In [90]:
# Add an MVP column to the dataset based only on the player names
mvp_players = [
    "Nikola Jokić", "Joel Embiid", "Giannis Antetokounmpo", "James Harden",
    "Russell Westbrook", "Stephen Curry", "Kevin Durant", "LeBron James",
    "Derrick Rose", "Kobe Bryant", "Dirk Nowitzki", "Steve Nash",
    "Kevin Garnett", "Tim Duncan", "Allen Iverson", "Shaquille O'Neal",
    "Karl Malone", "Michael Jordan", "David Robinson", "Hakeem Olajuwon",
    "Charles Barkley", "Magic Johnson", "Larry Bird", "Moses Malone",
    "Julius Erving", "Kareem Abdul-Jabbar", "Bill Walton"
]

# Add a new MVP column: 1 if the player is in the list, 0 otherwise
filtered_dataset["MVP"] = filtered_dataset["Player"].apply(
    lambda player: 1 if player in mvp_players else 0
)



# Show a preview of the dataset
filtered_dataset.head()

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_27912\4222391030.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dataset["MVP"] = filtered_dataset["Player"].apply(

,Player,Age,G,MP,FG%,3P%,FT%,PER GAME MP,PER GAME PTS,PER GAME TRB,PER GAME AST,PER GAME STL,PER GAME BLK,PER GAME TOV,MVP
0,Ibou Badji,21.0,17,199.0,0.632,NaN,0.5,11.7,1.7,2.8,0.8,0.1,1.2,0.8,0
1,Amari Bailey,19.0,3,15.0,0.286,0.000,0.5,5.0,1.7,0.7,0.3,0.0,0.0,0.3,0
2,Emoni Bates,20.0,10,76.0,0.240,0.250,0.5,7.6,1.8,1.0,0.6,0.1,0.2,0.1,0
3,Jules Bernard,24.0,6,28.0,0.250,0.125,NaN,4.7,1.2,0.8,0.8,0.2,0.2,0.3,0
4,Onuralp Bitim,24.0,2,6.0,0.000,0.000,NaN,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [91]:
from unidecode import unidecode

# Normalize player names in the MVP list and dataset
mvp_players_normalized = [unidecode(player.lower()) for player in mvp_players]

# Add a new MVP column: 1 if the normalized player is in the normalized MVP list, 0 otherwise
filtered_dataset["MVP"] = filtered_dataset["Player"].apply(
    lambda player: 1 if unidecode(player.lower()) in mvp_players_normalized else 0
)

# Show a preview of the dataset
print(filtered_dataset.head())

print("LeBron James")#as a test
print(filtered_dataset[filtered_dataset["Player"] == "LeBron James"])

          Player   Age   G     MP    FG%    3P%  FT%  PER GAME MP  \
0     Ibou Badji  21.0  17  199.0  0.632    NaN  0.5         11.7
1   Amari Bailey  19.0   3   15.0  0.286  0.000  0.5          5.0
2    Emoni Bates  20.0  10   76.0  0.240  0.250  0.5          7.6
3  Jules Bernard  24.0   6   28.0  0.250  0.125  NaN          4.7
4  Onuralp Bitim  24.0   2    6.0  0.000  0.000  NaN          3.0

   PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
0            1.7           2.8           0.8           0.1           1.2
1            1.7           0.7           0.3           0.0           0.0
2            1.8           1.0           0.6           0.1           0.2
3            1.2           0.8           0.8           0.2           0.2
4            0.0           0.0           0.0           0.0           0.0

   PER GAME TOV  MVP
0           0.8    0
1           0.3    0
2           0.1    0
3           0.3    0
4           0.0    0
LeBron James
            Player   Age   G      MP    FG%   3P%    FT%  PER GAME MP  \
1743  LeBron James  19.0  79  3122.0  0.417  0.29  0.754         39.5

      PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
1743           20.9           5.5           5.9           1.6           0.7

      PER GAME TOV  MVP
1743           3.5    1

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_27912\166321566.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dataset["MVP"] = filtered_dataset["Player"].apply(

NBA Rookie of the Year

Victor Wembanyama
Paolo Banchero
Scottie Barnes
LaMelo Ball
Ja Morant
Luka Dončić
Ben Simmons
Malcolm Brogdon
Karl-Anthony Towns
Andrew Wiggins
Michael Carter-Williams
Damian Lillard
Kyrie Irving
Blake Griffin
Tyreke Evans
Derrick Rose
Kevin Durant
Brandon Roy
Chris Paul
Emeka Okafor
LeBron James
Amar'e Stoudemire
Pau Gasol
Mike Miller
Steve Francis (Tie)
Elton Brand (Tie)
Vince Carter
Tim Duncan
Allen Iverson
Damon Stoudamire
Jason Kidd (Tie)
Grant Hill (Tie)
Chris Webber
Shaquille O'Neal
Larry Johnson
Derrick Coleman
David Robinson
Mitch Richmond
Mark Jackson
Chuck Person
Patrick Ewing
Michael Jordan
Ralph Sampson
Terry Cummings
Buck Williams
Darrell Griffith
Larry Bird
Phil Ford
Walter Davis
Adrian Dantley
Alvan Adams

In [100]:
from unidecode import unidecode


# Normalize player names in the ROY list and dataset
rookie_of_the_year_players_normalized = [unidecode(player.lower()) for player in rookie_of_the_year_players]
# List of NBA Rookie of the Year players
rookie_of_the_year_players = [
    "Victor Wembanyama", "Paolo Banchero", "Scottie Barnes", "LaMelo Ball", "Ja Morant", "Luka Dončić", 
    "Ben Simmons", "Malcolm Brogdon", "Karl-Anthony Towns", "Andrew Wiggins", "Michael Carter-Williams", 
    "Damian Lillard", "Kyrie Irving", "Blake Griffin", "Tyreke Evans", "Derrick Rose", "Kevin Durant", 
    "Brandon Roy", "Chris Paul", "Emeka Okafor", "LeBron James", "Amar'e Stoudemire", "Pau Gasol", 
    "Mike Miller", "Steve Francis", "Elton Brand", "Vince Carter", "Tim Duncan", "Allen Iverson", 
    "Damon Stoudamire", "Jason Kidd", "Grant Hill", "Chris Webber", "Shaquille O'Neal", "Larry Johnson", 
    "Derrick Coleman", "David Robinson", "Mitch Richmond", "Mark Jackson", "Chuck Person", "Patrick Ewing", 
    "Michael Jordan", "Ralph Sampson", "Terry Cummings", "Buck Williams", "Darrell Griffith", "Larry Bird", 
    "Phil Ford", "Walter Davis", "Adrian Dantley", "Alvan Adams"
]

# Normalize player names in the ROY list and dataset
rookie_of_the_year_players_normalized = [unidecode(player.lower()) for player in rookie_of_the_year_players]

# Add a new ROY column: 1 if the normalized player is in the normalized ROY list, 0 otherwise
filtered_dataset["ROY"] = filtered_dataset["Player"].apply(
    lambda player: 1 if unidecode(player.lower()) in rookie_of_the_year_players_normalized else 0
)
mvp_players_normalized = [unidecode(player.lower()) for player in mvp_players]

# Add a new MVP column: 1 if the normalized player is in the normalized MVP list, 0 otherwise
filtered_dataset["MVP"] = filtered_dataset["Player"].apply(
    lambda player: 1 if unidecode(player.lower()) in mvp_players_normalized else 0
)

# Show a preview of the dataset
print(filtered_dataset.head())

print("LeBron James")#as a test
print(filtered_dataset[filtered_dataset["Player"] == "LeBron James"])

          Player   Age   G     MP    FG%    3P%  FT%  PER GAME MP  \
0     Ibou Badji  21.0  17  199.0  0.632    NaN  0.5         11.7
1   Amari Bailey  19.0   3   15.0  0.286  0.000  0.5          5.0
2    Emoni Bates  20.0  10   76.0  0.240  0.250  0.5          7.6
3  Jules Bernard  24.0   6   28.0  0.250  0.125  NaN          4.7
4  Onuralp Bitim  24.0   2    6.0  0.000  0.000  NaN          3.0

   PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
0            1.7           2.8           0.8           0.1           1.2
1            1.7           0.7           0.3           0.0           0.0
2            1.8           1.0           0.6           0.1           0.2
3            1.2           0.8           0.8           0.2           0.2
4            0.0           0.0           0.0           0.0           0.0

   PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY
0           0.8    0                   0          0             0    0
1           0.3    0                   0          0             0    0
2           0.1    0                   0          0             0    0
3           0.3    0                   0          0             0    0
4           0.0    0                   0          0             0    0
LeBron James
            Player   Age   G      MP    FG%   3P%    FT%  PER GAME MP  \
1743  LeBron James  19.0  79  3122.0  0.417  0.29  0.754         39.5

      PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
1743           20.9           5.5           5.9           1.6           0.7

      PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY
1743           3.5    1                   1          1             1    1

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_27912\1518569239.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dataset["ROY"] = filtered_dataset["Player"].apply(
C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_27912\1518569239.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dataset["MVP"] = filtered_dataset["Player"].apply(

All defensive team

Draymond Green, Dennis Johnson, George Johnson, Derrick McKey, Bam Adebayo, Kareem Abdul-Jabbar, Victor Oladipo, Kevin McHale, Eric Bledsoe, Rudy Gobert, Patrick Ewing, Gary Payton, Moses Malone, Scott Wedman, Lionel Hollins, Paul Pressey, Don Chaney, Jrue Holiday, Danny Vranes, Tim Duncan, Caldwell Jones, Wayne Rollins, Michael Cooper, Jamaal Wilkes, Bruce Bowen, Jrue Holiday, Shane Battier, Tony Allen, Charles Oakley, Chris Paul, Robert Covington, Thabo Sefolosha, Maurice Cheeks, Alex Caruso, Anthony Davis, Herbert Jones, LeBron James, Rajon Rondo, Brook Lopez, Mark Eaton, Jaren Jackson Jr., Quinn Buckner, Sidney Moncrief, Mookie Blaylock, Derrick White, DeAndre Jordan, Artis Gilmore, Matisse Thybulle, Jrue Holiday, Dudley Bradley, Andrei Kirilenko, Don Buse, E. C. Coleman, Horace Grant, Nate McMillan, Alonzo Mourning, Eric Snow, Gerald Wallace, Hakeem Olajuwon, Jason Kidd, Eddie Johnson, Victor Wembanyama, Dave Cowens, Marc Gasol, Bobby Jones, Jaden McDaniels, Dwight Howard, Dan Roundfield, Tayshaun Prince, Jamaal Wilkes, Bob Dandridge, Bruce Bowen.

In [101]:
# List of players who made the All-Defensive Team
all_defensive_team_players = [
    "Draymond Green", "Dennis Johnson", "George Johnson", "Derrick McKey", "Bam Adebayo", "Kareem Abdul-Jabbar", 
    "Victor Oladipo", "Kevin McHale", "Eric Bledsoe", "Rudy Gobert", "Patrick Ewing", "Gary Payton", "Moses Malone", 
    "Scott Wedman", "Lionel Hollins", "Paul Pressey", "Don Chaney", "Jrue Holiday", "Danny Vranes", "Tim Duncan", 
    "Caldwell Jones", "Wayne Rollins", "Michael Cooper", "Jamaal Wilkes", "Bruce Bowen", "Jrue Holiday", "Shane Battier", 
    "Tony Allen", "Charles Oakley", "Chris Paul", "Robert Covington", "Thabo Sefolosha", "Maurice Cheeks", "Alex Caruso", 
    "Anthony Davis", "Herbert Jones", "LeBron James", "Rajon Rondo", "Brook Lopez", "Mark Eaton", "Jaren Jackson Jr.", 
    "Quinn Buckner", "Sidney Moncrief", "Mookie Blaylock", "Derrick White", "DeAndre Jordan", "Artis Gilmore", 
    "Matisse Thybulle", "Jrue Holiday", "Dudley Bradley", "Andrei Kirilenko", "Don Buse", "E. C. Coleman", "Horace Grant", 
    "Nate McMillan", "Alonzo Mourning", "Eric Snow", "Gerald Wallace", "Hakeem Olajuwon", "Jason Kidd", "Eddie Johnson", 
    "Victor Wembanyama", "Dave Cowens", "Marc Gasol", "Bobby Jones", "Jaden McDaniels", "Dwight Howard", "Dan Roundfield", 
    "Tayshaun Prince", "Jamaal Wilkes", "Bob Dandridge", "Bruce Bowen"
]

# Normalize player names in the All-Defensive Team list
all_defensive_team_players_normalized = [unidecode(player.lower()) for player in all_defensive_team_players]

# Add a new All-Defensive Team column: 1 if the normalized player is in the normalized All-Defensive Team list, 0 otherwise
filtered_dataset["All-Defensive Team"] = filtered_dataset["Player"].apply(
    lambda player: 1 if unidecode(player.lower()) in all_defensive_team_players_normalized else 0
)

# Show a preview of the dataset
print(filtered_dataset.head())

print("LeBron James")#as a test
print(filtered_dataset[filtered_dataset["Player"] == "LeBron James"])

          Player   Age   G     MP    FG%    3P%  FT%  PER GAME MP  \
0     Ibou Badji  21.0  17  199.0  0.632    NaN  0.5         11.7
1   Amari Bailey  19.0   3   15.0  0.286  0.000  0.5          5.0
2    Emoni Bates  20.0  10   76.0  0.240  0.250  0.5          7.6
3  Jules Bernard  24.0   6   28.0  0.250  0.125  NaN          4.7
4  Onuralp Bitim  24.0   2    6.0  0.000  0.000  NaN          3.0

   PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
0            1.7           2.8           0.8           0.1           1.2
1            1.7           0.7           0.3           0.0           0.0
2            1.8           1.0           0.6           0.1           0.2
3            1.2           0.8           0.8           0.2           0.2
4            0.0           0.0           0.0           0.0           0.0

   PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY
0           0.8    0                   0          0             0    0
1           0.3    0                   0          0             0    0
2           0.1    0                   0          0             0    0
3           0.3    0                   0          0             0    0
4           0.0    0                   0          0             0    0
LeBron James
            Player   Age   G      MP    FG%   3P%    FT%  PER GAME MP  \
1743  LeBron James  19.0  79  3122.0  0.417  0.29  0.754         39.5

      PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
1743           20.9           5.5           5.9           1.6           0.7

      PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY
1743           3.5    1                   1          1             1    1

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_27912\3326614909.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dataset["All-Defensive Team"] = filtered_dataset["Player"].apply(

Final MVP

Jo Jo White, Dirk Nowitzki, Dennis Johnson, Tim Duncan, Dwyane Wade, Tony Parker, Moses Malone, Kawhi Leonard, Giannis Antetokounmpo, Jerry West, Michael Jordan, Wilt Chamberlain, Shaquille O'Neal, James Worthy, Nikola Jokić, Kevin Durant, Larry Bird, Paul Pierce, John Havlicek, Andre Iguodala, Jaylen Brown, Chauncey Billups, Rick Barry, LeBron James, Cedric Maxwell, Kobe Bryant, Wes Unseld, Hakeem Olajuwon, Stephen Curry, Bill Walton, Magic Johnson, Willis Reed, Kareem Abdul-Jabbar, Isiah Thomas, Lew Alcindor.

In [102]:
import pandas as pd
from unidecode import unidecode

# Create the list of NBA Finals MVPs
final_mvp_list = [
    "Jo Jo White", "Dirk Nowitzki", "Dennis Johnson", "Tim Duncan", "Dwyane Wade", 
    "Tony Parker", "Moses Malone", "Kawhi Leonard", "Giannis Antetokounmpo", 
    "Jerry West", "Michael Jordan", "Wilt Chamberlain", "Shaquille O'Neal", 
    "James Worthy", "Nikola Jokić", "Kevin Durant", "Larry Bird", "Paul Pierce", 
    "John Havlicek", "Andre Iguodala", "Jaylen Brown", "Chauncey Billups", 
    "Rick Barry", "LeBron James", "Cedric Maxwell", "Kobe Bryant", "Wes Unseld", 
    "Hakeem Olajuwon", "Stephen Curry", "Bill Walton", "Magic Johnson", 
    "Willis Reed", "Kareem Abdul-Jabbar", "Isiah Thomas", "Lew Alcindor"
]

# Normalize player names in the Finals MVP list
final_mvp_list_normalized = [unidecode(player.lower()) for player in final_mvp_list]

# Add a new Finals MVP column: 1 if the normalized player is in the normalized Finals MVP list, 0 otherwise
filtered_dataset["Final MVP"] = filtered_dataset["Player"].apply(
    lambda player: 1 if unidecode(player.lower()) in final_mvp_list_normalized else 0
)

# Display the updated DataFrame
print(filtered_dataset)

print("LeBron James")#as a test
print(filtered_dataset[filtered_dataset["Player"] == "LeBron James"])

print("luka doncic")#as a test
print(filtered_dataset[filtered_dataset["Player"] == "Luka Doncic"])

             Player   Age   G     MP    FG%    3P%    FT%  PER GAME MP  \
0        Ibou Badji  21.0  17  199.0  0.632    NaN  0.500         11.7
1      Amari Bailey  19.0   3   15.0  0.286  0.000  0.500          5.0
2       Emoni Bates  20.0  10   76.0  0.240  0.250  0.500          7.6
3     Jules Bernard  24.0   6   28.0  0.250  0.125    NaN          4.7
4     Onuralp Bitim  24.0   2    6.0  0.000  0.000    NaN          3.0
...             ...   ...  ..    ...    ...    ...    ...          ...
5402    Red Wallace  28.0  61    NaN  0.278    NaN  0.541          NaN
5403     Jake Weber  28.0  50    NaN  0.292    NaN  0.696          NaN
5404     Ray Wertis  23.0  61    NaN  0.216    NaN  0.615          NaN
5405  Max Zaslofsky  21.0  61    NaN  0.329    NaN  0.737          NaN
5406   Harry Zeller  27.0  48    NaN  0.314    NaN  0.689          NaN

      PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
0               1.7           2.8           0.8           0.1           1.2
1               1.7           0.7           0.3           0.0           0.0
2               1.8           1.0           0.6           0.1           0.2
3               1.2           0.8           0.8           0.2           0.2
4               0.0           0.0           0.0           0.0           0.0
...             ...           ...           ...           ...           ...
5402            9.1           NaN           1.0           NaN           NaN
5403            3.5           NaN           0.1           NaN           NaN
5404            3.5           NaN           0.6           NaN           NaN
5405           14.4           NaN           0.7           NaN           NaN
5406            7.5           NaN           0.6           NaN           NaN

      PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY
0              0.8    0                   0          0             0    0
1              0.3    0                   0          0             0    0
2              0.1    0                   0          0             0    0
3              0.3    0                   0          0             0    0
4              0.0    0                   0          0             0    0
...            ...  ...                 ...        ...           ...  ...
5402           NaN    0                   0          0             0    0
5403           NaN    0                   0          0             0    0
5404           NaN    0                   0          0             0    0
5405           NaN    0                   0          0             0    0
5406           NaN    0                   0          0             0    0

[5407 rows x 19 columns]
LeBron James
            Player   Age   G      MP    FG%   3P%    FT%  PER GAME MP  \
1743  LeBron James  19.0  79  3122.0  0.417  0.29  0.754         39.5

      PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
1743           20.9           5.5           5.9           1.6           0.7

      PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY
1743           3.5    1                   1          1             1    1
luka doncic
          Player   Age   G      MP    FG%    3P%    FT%  PER GAME MP  \
550  Luka Doncic  19.0  72  2318.0  0.427  0.327  0.713         32.2

     PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
550           21.2           7.8           6.0           1.1           0.3

     PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY
550           3.4    0                   0          0             1    1

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_27912\946015999.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dataset["Final MVP"] = filtered_dataset["Player"].apply(

All league teams

Adrian Dantley, Al Cervi, Al Horford, Al Jefferson, Alex English, Alex Groza, Alvin Robertson, Amar'e Stoudemire, Anfernee Hardaway, Andre Drummond, Andrew Bogut, Andrew Bynum, Andy Phillip, Anthony Davis, Anthony Edwards, Anthony Mason, Antonio McDyess, Archie Clark, Arnie Risen, Artis Gilmore, Baron Davis, Bailey Howell, Ben Simmons, Bernard King, Bill Melchionni, Bill Sharman, Bill Walton, Billy Cunningham, Billy Knight, Blake Griffin, Bob Cousy, Bob Dandridge, Bob Davies, Bob Feerick, Bob Love, Bob McAdoo, Bob Netolicky, Bob Pettit, Bob Verga, Bobby Jones, Bobby Wanzer, Bones McKinney, Brad Daugherty, Bradley Beal, Brandon Roy, Buck Williams, Buddy Jeannette, Carlos Boozer, Carmelo Anthony, Chauncey Billups, Charlie Scott, Charlie Williams, Chick Halbert, Chris Bosh, Chris Mullin, Chris Paul, Chris Webber, Chuck Person, Cincy Powell, Cliff Hagan, Clyde Drexler, Clyde Lovellette, Connie Hawkins, Dale Ellis, Damian Lillard, Dan Issel, Dan Roundfield, Danny Ainge, Dave Bing, Dave Cowens, Dave DeBusschere, David Lee, David Robinson, David Thompson, De'Aaron Fox, DeAndre Jordan, DeMarcus Cousins, DeMar DeRozan, Dennis Johnson, Dennis Rodman, Derrick Coleman, Derrick Rose, Dikembe Mutombo, Dirk Nowitzki, Donovan Mitchell, Dolph Schayes, Domantas Sabonis, Doug Moe, Dražen Petrović, Draymond Green, Dwyane Wade, Dwight Howard, Earl Monroe, Eddie Jones, Ed Macauley, Ed Sadowski, Elgin Baylor, Elvin Hayes, Elton Brand, Ernie Calverley, Fat Lever, Frank Ramsey, Frankie Brian, Fred Schaus, Fred Scolari, Gail Goodrich, Gary Payton, Gene Shue, George Gervin, George Mikan, George McGinnis, George Yardley, Gerald Wallace, Goran Dragić, Grant Hill, Gus Johnson, Gus Williams, Hakeem Olajuwon, Hal Greer, Harry Gallatin, Howie Dallmar, Isaiah Thomas, Isiah Thomas, J.J. Redick, Ja Morant, Jack George, Jack Sikma, Jack Twyman, Jamal Mashburn, James Harden, James Silas, James Worthy, Jason Kidd, Jayson Tatum, Jaylen Brown, Jerry Lucas, Jerry Stackhouse, Jerry West, Jim Paxson, Jimmy Butler, Jimmy Jones, Juwan Howard, Jo Jo White, Joakim Noah, Joe Caldwell, Joe Dumars, Joe Fulks, Joe Johnson, John Beasley, John Brisker, John Havlicek, John Logan, John Starks, John Stockton, Johnny Green, Julius Erving, Julius Randle, Kareem Abdul-Jabbar, Karl-Anthony Towns, Karl Malone, Kawhi Leonard, Kelly Tripucka, Kevin Durant, Kevin Garnett, Kevin Johnson, Kevin Love, Kevin McHale, Kevin Willis, Khris Middleton, Klay Thompson, Kobe Bryant, Kyle Lowry, Kyrie Irving, LaMarcus Aldridge, Larry Bird, Larry Brown, Larry Cannon, Larry Costello, Larry Foust, Larry Johnson, Latrell Sprewell, LeBron James, Lou Hudson, Louie Dampier, Luka Dončić, Mack Calvin, Magic Johnson, Manu Ginóbili, Marcus Camby, Marc Gasol, Mark Aguirre, Mark Eaton, Mark Price, Marques Johnson, Marvin Barnes, Maurice Cheeks, Maurice Lucas, Maurice Stokes, Mel Daniels, Metta World Peace, Michael Jordan, Michael Redd, Mikal Bridges, Mitch Richmond, Mo Williams, Moses Malone, Myles Turner, Nate Archibald, Nate Thurmond, Neil Johnston, Norm Nixon, Norm Van Lier, Oscar Robertson, Otis Birdsong, P.J. Brown, Pascal Siakam, Paul Arizin, Paul George, Paul Pierce, Paul Seymour, Paul Westphal, Pau Gasol, Peja Stojaković, Penny Hardaway, Pete Maravich, Phil Chenier, Phil Ford, Phil Smith, Ralph Beard, Ralph Sampson, Randy Smith, Ray Allen, Reggie Miller, Reggie Theus, Rick Barry, Rick Fox, Ricky Rubio, Robert Parish, Robert Williams III, Ron Boone, Ron Harper, Rudy Gobert, Sam Cassell, Sam Jones, Sam Lacey, Sam Perkins, Scottie Pippen, Sean Elliott, Shawn Kemp, Shawn Marion, Sidney Moncrief, Sleepy Floyd, Slater Martin, Spencer Haywood, Stan Love, Stan Miasek, Stephon Marbury, Stephen Curry, Steve Nash, Steve Smith, Swen Nater, Terry Cummings, Terry Porter, Thabo Sefolosha, Tiny Archibald, Tom Chambers, Tom Gola, Tony Allen, Tony Parker, Trae Young, Truck Robinson, Tyson Chandler, Vince Carter, Victor Oladipo, Vin Baker, Vlade Divac, Walt Bellamy, Walt Frazier, Warren Jabali, Wayne Embry, Wes Unseld, Willis Reed, Wilson Chandler, Wilt Chamberlain, World B. Free, Zach Randolph, Zelmo Beaty.

In [103]:
# List of players who made the All-NBA Team
all_nba_team_players = [
    "Adrian Dantley", "Al Cervi", "Al Horford", "Al Jefferson", "Alex English", "Alex Groza", "Alvin Robertson", "Amar'e Stoudemire", 
    "Anfernee Hardaway", "Andre Drummond", "Andrew Bogut", "Andrew Bynum", "Andy Phillip", "Anthony Davis", "Anthony Edwards", 
    "Anthony Mason", "Antonio McDyess", "Archie Clark", "Arnie Risen", "Artis Gilmore", "Baron Davis", "Bailey Howell", "Ben Simmons", 
    "Bernard King", "Bill Melchionni", "Bill Sharman", "Bill Walton", "Billy Cunningham", "Billy Knight", "Blake Griffin", "Bob Cousy", 
    "Bob Dandridge", "Bob Davies", "Bob Feerick", "Bob Love", "Bob McAdoo", "Bob Netolicky", "Bob Pettit", "Bob Verga", "Bobby Jones", 
    "Bobby Wanzer", "Bones McKinney", "Brad Daugherty", "Bradley Beal", "Brandon Roy", "Buck Williams", "Buddy Jeannette", "Carlos Boozer", 
    "Carmelo Anthony", "Chauncey Billups", "Charlie Scott", "Charlie Williams", "Chick Halbert", "Chris Bosh", "Chris Mullin", "Chris Paul", 
    "Chris Webber", "Chuck Person", "Cincy Powell", "Cliff Hagan", "Clyde Drexler", "Clyde Lovellette", "Connie Hawkins", "Dale Ellis", 
    "Damian Lillard", "Dan Issel", "Dan Roundfield", "Danny Ainge", "Dave Bing", "Dave Cowens", "Dave DeBusschere", "David Lee", 
    "David Robinson", "David Thompson", "De'Aaron Fox", "DeAndre Jordan", "DeMarcus Cousins", "DeMar DeRozan", "Dennis Johnson", 
    "Dennis Rodman", "Derrick Coleman", "Derrick Rose", "Dikembe Mutombo", "Dirk Nowitzki", "Donovan Mitchell", "Dolph Schayes", 
    "Domantas Sabonis", "Doug Moe", "Dražen Petrović", "Draymond Green", "Dwyane Wade", "Dwight Howard", "Earl Monroe", "Eddie Jones", 
    "Ed Macauley", "Ed Sadowski", "Elgin Baylor", "Elvin Hayes", "Elton Brand", "Ernie Calverley", "Fat Lever", "Frank Ramsey", 
    "Frankie Brian", "Fred Schaus", "Fred Scolari", "Gail Goodrich", "Gary Payton", "Gene Shue", "George Gervin", "George Mikan", 
    "George McGinnis", "George Yardley", "Gerald Wallace", "Goran Dragić", "Grant Hill", "Gus Johnson", "Gus Williams", "Hakeem Olajuwon", 
    "Hal Greer", "Harry Gallatin", "Howie Dallmar", "Isaiah Thomas", "Isiah Thomas", "J.J. Redick", "Ja Morant", "Jack George", "Jack Sikma", 
    "Jack Twyman", "Jamal Mashburn", "James Harden", "James Silas", "James Worthy", "Jason Kidd", "Jayson Tatum", "Jaylen Brown", 
    "Jerry Lucas", "Jerry Stackhouse", "Jerry West", "Jim Paxson", "Jimmy Butler", "Jimmy Jones", "Juwan Howard", "Jo Jo White", 
    "Joakim Noah", "Joe Caldwell", "Joe Dumars", "Joe Fulks", "Joe Johnson", "John Beasley", "John Brisker", "John Havlicek", "John Logan", 
    "John Starks", "John Stockton", "Johnny Green", "Julius Erving", "Julius Randle", "Kareem Abdul-Jabbar", "Karl-Anthony Towns", 
    "Karl Malone", "Kawhi Leonard", "Kelly Tripucka", "Kevin Durant", "Kevin Garnett", "Kevin Johnson", "Kevin Love", "Kevin McHale", 
    "Kevin Willis", "Khris Middleton", "Klay Thompson", "Kobe Bryant", "Kyle Lowry", "Kyrie Irving", "LaMarcus Aldridge", "Larry Bird", 
    "Larry Brown", "Larry Cannon", "Larry Costello", "Larry Foust", "Larry Johnson", "Latrell Sprewell", "LeBron James", "Lou Hudson", 
    "Louie Dampier", "Luka Dončić", "Mack Calvin", "Magic Johnson", "Manu Ginóbili", "Marcus Camby", "Marc Gasol", "Mark Aguirre", 
    "Mark Eaton", "Mark Price", "Marques Johnson", "Marvin Barnes", "Maurice Cheeks", "Maurice Lucas", "Maurice Stokes", "Mel Daniels", 
    "Metta World Peace", "Michael Jordan", "Michael Redd", "Mikal Bridges", "Mitch Richmond", "Mo Williams", "Moses Malone", "Myles Turner", 
    "Nate Archibald", "Nate Thurmond", "Neil Johnston", "Norm Nixon", "Norm Van Lier", "Oscar Robertson", "Otis Birdsong", "P.J. Brown", 
    "Pascal Siakam", "Paul Arizin", "Paul George", "Paul Pierce", "Paul Seymour", "Paul Westphal", "Pau Gasol", "Peja Stojaković", 
    "Penny Hardaway", "Pete Maravich", "Phil Chenier", "Phil Ford", "Phil Smith", "Ralph Beard", "Ralph Sampson", "Randy Smith", "Ray Allen", 
    "Reggie Miller", "Reggie Theus", "Rick Barry", "Rick Fox", "Ricky Rubio", "Robert Parish", "Robert Williams III", "Ron Boone", 
    "Ron Harper", "Rudy Gobert", "Sam Cassell", "Sam Jones", "Sam Lacey", "Sam Perkins", "Scottie Pippen", "Sean Elliott", "Shawn Kemp", 
    "Shawn Marion", "Sidney Moncrief", "Sleepy Floyd", "Slater Martin", "Spencer Haywood", "Stan Love", "Stan Miasek", "Stephon Marbury", 
    "Stephen Curry", "Steve Nash", "Steve Smith", "Swen Nater", "Terry Cummings", "Terry Porter", "Thabo Sefolosha", "Tiny Archibald", 
    "Tom Chambers", "Tom Gola", "Tony Allen", "Tony Parker", "Trae Young", "Truck Robinson", "Tyson Chandler", "Vince Carter", 
    "Victor Oladipo", "Vin Baker", "Vlade Divac", "Walt Bellamy", "Walt Frazier", "Warren Jabali", "Wayne Embry", "Wes Unseld", 
    "Willis Reed", "Wilson Chandler", "Wilt Chamberlain", "World B. Free", "Zach Randolph", "Zelmo Beaty"
]

# Normalize player names in the All-NBA Team list
all_nba_team_players_normalized = [unidecode(player.lower()) for player in all_nba_team_players]

# Add a new All-NBA Team column: 1 if the normalized player is in the normalized All-NBA Team list, 0 otherwise
filtered_dataset["All-NBA Team"] = filtered_dataset["Player"].apply(
    lambda player: 1 if unidecode(player.lower()) in all_nba_team_players_normalized else 0
)
# Show a preview of the dataset
print(filtered_dataset.head())
print(filtered_dataset[filtered_dataset["Player"].isin(["LeBron James", "Nikola Jokic", "Luka Doncic"])])
# Show a preview of the dataset
print(filtered_dataset.head())
print(filtered_dataset[filtered_dataset["Player"].isin(["LeBron James", "Nikola Jokic", "Luka Doncic"])])

          Player   Age   G     MP    FG%    3P%  FT%  PER GAME MP  \
0     Ibou Badji  21.0  17  199.0  0.632    NaN  0.5         11.7
1   Amari Bailey  19.0   3   15.0  0.286  0.000  0.5          5.0
2    Emoni Bates  20.0  10   76.0  0.240  0.250  0.5          7.6
3  Jules Bernard  24.0   6   28.0  0.250  0.125  NaN          4.7
4  Onuralp Bitim  24.0   2    6.0  0.000  0.000  NaN          3.0

   PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
0            1.7           2.8           0.8           0.1           1.2
1            1.7           0.7           0.3           0.0           0.0
2            1.8           1.0           0.6           0.1           0.2
3            1.2           0.8           0.8           0.2           0.2
4            0.0           0.0           0.0           0.0           0.0

   PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY
0           0.8    0                   0          0             0    0
1           0.3    0                   0          0             0    0
2           0.1    0                   0          0             0    0
3           0.3    0                   0          0             0    0
4           0.0    0                   0          0             0    0
            Player   Age   G      MP    FG%    3P%    FT%  PER GAME MP  \
550    Luka Doncic  19.0  72  2318.0  0.427  0.327  0.713         32.2
857   Nikola Jokic  20.0  80  1733.0  0.512  0.333  0.811         21.7
1743  LeBron James  19.0  79  3122.0  0.417  0.290  0.754         39.5

      PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
550            21.2           7.8           6.0           1.1           0.3
857            10.0           7.0           2.4           1.0           0.6
1743           20.9           5.5           5.9           1.6           0.7

      PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY
550            3.4    0                   0          0             1    1
857            1.3    1                   0          1             0    0
1743           3.5    1                   1          1             1    1
          Player   Age   G     MP    FG%    3P%  FT%  PER GAME MP  \
0     Ibou Badji  21.0  17  199.0  0.632    NaN  0.5         11.7
1   Amari Bailey  19.0   3   15.0  0.286  0.000  0.5          5.0
2    Emoni Bates  20.0  10   76.0  0.240  0.250  0.5          7.6
3  Jules Bernard  24.0   6   28.0  0.250  0.125  NaN          4.7
4  Onuralp Bitim  24.0   2    6.0  0.000  0.000  NaN          3.0

   PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
0            1.7           2.8           0.8           0.1           1.2
1            1.7           0.7           0.3           0.0           0.0
2            1.8           1.0           0.6           0.1           0.2
3            1.2           0.8           0.8           0.2           0.2
4            0.0           0.0           0.0           0.0           0.0

   PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY
0           0.8    0                   0          0             0    0
1           0.3    0                   0          0             0    0
2           0.1    0                   0          0             0    0
3           0.3    0                   0          0             0    0
4           0.0    0                   0          0             0    0
            Player   Age   G      MP    FG%    3P%    FT%  PER GAME MP  \
550    Luka Doncic  19.0  72  2318.0  0.427  0.327  0.713         32.2
857   Nikola Jokic  20.0  80  1733.0  0.512  0.333  0.811         21.7
1743  LeBron James  19.0  79  3122.0  0.417  0.290  0.754         39.5

      PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
550            21.2           7.8           6.0           1.1           0.3
857            10.0           7.0           2.4           1.0           0.6
1743           20.9           5.5           5.9           1.6           0.7

      PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY
550            3.4    0                   0          0             1    1
857            1.3    1                   0          1             0    0
1743           3.5    1                   1          1             1    1

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_27912\4042095824.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dataset["All-NBA Team"] = filtered_dataset["Player"].apply(

success variable

In [105]:
# Create a success variable based on the awards
filtered_dataset["Success"] = (
	filtered_dataset["MVP"] + 
	filtered_dataset["ROY"] + 
	filtered_dataset["All-Defensive Team"] + 
	filtered_dataset["Final MVP"] + 
	filtered_dataset["All-NBA Team"]
)

# Show a preview of the dataset with the new Success column
print(filtered_dataset.head())
print(filtered_dataset[filtered_dataset["Player"].isin(["LeBron James", "Nikola Jokic", "Luka Doncic"])])

          Player   Age   G     MP    FG%    3P%  FT%  PER GAME MP  \
0     Ibou Badji  21.0  17  199.0  0.632    NaN  0.5         11.7
1   Amari Bailey  19.0   3   15.0  0.286  0.000  0.5          5.0
2    Emoni Bates  20.0  10   76.0  0.240  0.250  0.5          7.6
3  Jules Bernard  24.0   6   28.0  0.250  0.125  NaN          4.7
4  Onuralp Bitim  24.0   2    6.0  0.000  0.000  NaN          3.0

   PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
0            1.7           2.8           0.8           0.1           1.2
1            1.7           0.7           0.3           0.0           0.0
2            1.8           1.0           0.6           0.1           0.2
3            1.2           0.8           0.8           0.2           0.2
4            0.0           0.0           0.0           0.0           0.0

   PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY  \
0           0.8    0                   0          0             0    0
1           0.3    0                   0          0             0    0
2           0.1    0                   0          0             0    0
3           0.3    0                   0          0             0    0
4           0.0    0                   0          0             0    0

   Success
0        0
1        0
2        0
3        0
4        0
            Player   Age   G      MP    FG%    3P%    FT%  PER GAME MP  \
550    Luka Doncic  19.0  72  2318.0  0.427  0.327  0.713         32.2
857   Nikola Jokic  20.0  80  1733.0  0.512  0.333  0.811         21.7
1743  LeBron James  19.0  79  3122.0  0.417  0.290  0.754         39.5

      PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
550            21.2           7.8           6.0           1.1           0.3
857            10.0           7.0           2.4           1.0           0.6
1743           20.9           5.5           5.9           1.6           0.7

      PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY  \
550            3.4    0                   0          0             1    1
857            1.3    1                   0          1             0    0
1743           3.5    1                   1          1             1    1

      Success
550         2
857         2
1743        5

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_27912\3440167024.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dataset["Success"] = (

In [107]:
# Remove all players with a success score of 0
filtered_dataset = filtered_dataset[filtered_dataset["Success"] > 0]

# Show a preview of the updated dataset
print(filtered_dataset.head())
print(filtered_dataset[filtered_dataset["Player"].isin(["LeBron James", "Nikola Jokic", "Luka Doncic"])])

                Player   Age   G      MP    FG%    3P%    FT%  PER GAME MP  \
89   Victor Wembanyama  20.0  52  1481.0  0.467  0.318  0.813         28.5
94      Paolo Banchero  20.0  72  2430.0  0.427  0.298  0.738         33.8
182     Scottie Barnes  20.0  74  2617.0  0.492  0.301  0.735         35.4
229      Herbert Jones  23.0  78  2335.0  0.476  0.337  0.840         29.9
308        LaMelo Ball  19.0  51  1469.0  0.436  0.352  0.758         28.8

     PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
89            20.7          10.1           3.3           1.3           3.3
94            20.0           6.9           3.7           0.8           0.5
182           15.3           7.5           3.5           1.1           0.7
229            9.5           3.8           2.1           1.7           0.8
308           15.7           5.9           6.1           1.6           0.4

     PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY  \
89            3.4    0                   1          0             0    1
94            2.8    0                   0          0             0    1
182           1.8    0                   0          0             0    1
229           1.3    0                   1          0             0    0
308           2.8    0                   0          0             0    1

     Success
89         2
94         1
182        1
229        1
308        1
            Player   Age   G      MP    FG%    3P%    FT%  PER GAME MP  \
550    Luka Doncic  19.0  72  2318.0  0.427  0.327  0.713         32.2
857   Nikola Jokic  20.0  80  1733.0  0.512  0.333  0.811         21.7
1743  LeBron James  19.0  79  3122.0  0.417  0.290  0.754         39.5

      PER GAME  PTS  PER GAME TRB  PER GAME AST  PER GAME STL  PER GAME BLK  \
550            21.2           7.8           6.0           1.1           0.3
857            10.0           7.0           2.4           1.0           0.6
1743           20.9           5.5           5.9           1.6           0.7

      PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY  \
550            3.4    0                   0          0             1    1
857            1.3    1                   0          1             0    0
1743           3.5    1                   1          1             1    1

      Success
550         2
857         2
1743        5

In [108]:
# Create a new column 'Success Category' based on the 'Success' score
filtered_dataset["Success Category"] = filtered_dataset["Success"].apply(lambda x: "low success" if x == 1 else "high success")

# Show a preview of the updated dataset
print(filtered_dataset.head())
print(filtered_dataset[filtered_dataset["Player"].isin(["LeBron James", "Nikola Jokic", "Luka Doncic"])])

                Player   Age   G      MP    FG%    3P%    FT%  PER GAME MP  \
89   Victor Wembanyama  20.0  52  1481.0  0.467  0.318  0.813         28.5
94      Paolo Banchero  20.0  72  2430.0  0.427  0.298  0.738         33.8
182     Scottie Barnes  20.0  74  2617.0  0.492  0.301  0.735         35.4
229      Herbert Jones  23.0  78  2335.0  0.476  0.337  0.840         29.9
308        LaMelo Ball  19.0  51  1469.0  0.436  0.352  0.758         28.8

     PER GAME  PTS  PER GAME TRB  ...  PER GAME STL  PER GAME BLK  \
89            20.7          10.1  ...           1.3           3.3
94            20.0           6.9  ...           0.8           0.5
182           15.3           7.5  ...           1.1           0.7
229            9.5           3.8  ...           1.7           0.8
308           15.7           5.9  ...           1.6           0.4

     PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY  \
89            3.4    0                   1          0             0    1
94            2.8    0                   0          0             0    1
182           1.8    0                   0          0             0    1
229           1.3    0                   1          0             0    0
308           2.8    0                   0          0             0    1

     Success  Success Category
89         2      high success
94         1       low success
182        1       low success
229        1       low success
308        1       low success

[5 rows x 21 columns]
            Player   Age   G      MP    FG%    3P%    FT%  PER GAME MP  \
550    Luka Doncic  19.0  72  2318.0  0.427  0.327  0.713         32.2
857   Nikola Jokic  20.0  80  1733.0  0.512  0.333  0.811         21.7
1743  LeBron James  19.0  79  3122.0  0.417  0.290  0.754         39.5

      PER GAME  PTS  PER GAME TRB  ...  PER GAME STL  PER GAME BLK  \
550            21.2           7.8  ...           1.1           0.3
857            10.0           7.0  ...           1.0           0.6
1743           20.9           5.5  ...           1.6           0.7

      PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY  \
550            3.4    0                   0          0             1    1
857            1.3    1                   0          1             0    0
1743           3.5    1                   1          1             1    1

      Success  Success Category
550         2      high success
857         2      high success
1743        5      high success

[3 rows x 21 columns]

In [109]:
from IPython.display import display

# Display the entire dataset
display(filtered_dataset)

,Player,Age,G,MP,FG%,3P%,FT%,PER GAME MP,PER GAME PTS,PER GAME TRB,...,PER GAME STL,PER GAME BLK,PER GAME TOV,MVP,All-Defensive Team,Final MVP,All-NBA Team,ROY,Success,Success Category
89,Victor Wembanyama,20.0,52,1481.0,0.467,0.318,0.813,28.5,20.7,10.1,...,1.3,3.3,3.4,0,1,0,0,1,2,high success
94,Paolo Banchero,20.0,72,2430.0,0.427,0.298,0.738,33.8,20.0,6.9,...,0.8,0.5,2.8,0,0,0,0,1,1,low success
182,Scottie Barnes,20.0,74,2617.0,0.492,0.301,0.735,35.4,15.3,7.5,...,1.1,0.7,1.8,0,0,0,0,1,1,low success
229,Herbert Jones,23.0,78,2335.0,0.476,0.337,0.840,29.9,9.5,3.8,...,1.7,0.8,1.3,0,1,0,0,0,1,low success
308,LaMelo Ball,19.0,51,1469.0,0.436,0.352,0.758,28.8,15.7,5.9,...,1.6,0.4,2.8,0,0,0,0,1,1,low success
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5328,John Logan,26.0,61,NaN,0.278,NaN,0.748,NaN,12.6,NaN,...,NaN,NaN,NaN,0,0,0,1,0,1,low success
5338,Bones McKinney,28.0,58,NaN,0.279,NaN,0.690,NaN,12.0,NaN,...,NaN,NaN,NaN,0,0,0,1,0,1,low success
5341,Stan Miasek,23.0,60,NaN,0.287,NaN,0.605,NaN,14.9,NaN,...,NaN,NaN,NaN,0,0,0,1,0,1,low success
5375,Ed Sadowski,31.0,53,NaN,0.369,NaN,0.668,NaN,16.5,NaN,...,NaN,NaN,NaN,0,0,0,1,0,1,low success
5381,Fred Scolari,24.0,58,NaN,0.294,NaN,0.811,NaN,12.6,NaN,...,NaN,NaN,NaN,0,0,0,1,0,1,low success

In [111]:
# Replace all NaN values with 0
filtered_dataset = filtered_dataset.fillna(0)

# Show a preview of the updated dataset
print(filtered_dataset.head())

                Player   Age   G      MP    FG%    3P%    FT%  PER GAME MP  \
89   Victor Wembanyama  20.0  52  1481.0  0.467  0.318  0.813         28.5
94      Paolo Banchero  20.0  72  2430.0  0.427  0.298  0.738         33.8
182     Scottie Barnes  20.0  74  2617.0  0.492  0.301  0.735         35.4
229      Herbert Jones  23.0  78  2335.0  0.476  0.337  0.840         29.9
308        LaMelo Ball  19.0  51  1469.0  0.436  0.352  0.758         28.8

     PER GAME  PTS  PER GAME TRB  ...  PER GAME STL  PER GAME BLK  \
89            20.7          10.1  ...           1.3           3.3
94            20.0           6.9  ...           0.8           0.5
182           15.3           7.5  ...           1.1           0.7
229            9.5           3.8  ...           1.7           0.8
308           15.7           5.9  ...           1.6           0.4

     PER GAME TOV  MVP  All-Defensive Team  Final MVP  All-NBA Team  ROY  \
89            3.4    0                   1          0             0    1
94            2.8    0                   0          0             0    1
182           1.8    0                   0          0             0    1
229           1.3    0                   1          0             0    0
308           2.8    0                   0          0             0    1

     Success  Success Category
89         2      high success
94         1       low success
182        1       low success
229        1       low success
308        1       low success

[5 rows x 21 columns]

In [112]:
# Add the Season column back to the filtered_dataset
filtered_dataset["Season"] = data_filtered["Season"]

# Show a preview of the updated dataset
print(filtered_dataset.head())
print(filtered_dataset[filtered_dataset["Player"].isin(["LeBron James", "Nikola Jokic", "Luka Doncic"])])

                Player   Age   G      MP    FG%    3P%    FT%  PER GAME MP  \
89   Victor Wembanyama  20.0  52  1481.0  0.467  0.318  0.813         28.5
94      Paolo Banchero  20.0  72  2430.0  0.427  0.298  0.738         33.8
182     Scottie Barnes  20.0  74  2617.0  0.492  0.301  0.735         35.4
229      Herbert Jones  23.0  78  2335.0  0.476  0.337  0.840         29.9
308        LaMelo Ball  19.0  51  1469.0  0.436  0.352  0.758         28.8

     PER GAME  PTS  PER GAME TRB  ...  PER GAME BLK  PER GAME TOV  MVP  \
89            20.7          10.1  ...           3.3           3.4    0
94            20.0           6.9  ...           0.5           2.8    0
182           15.3           7.5  ...           0.7           1.8    0
229            9.5           3.8  ...           0.8           1.3    0
308           15.7           5.9  ...           0.4           2.8    0

     All-Defensive Team  Final MVP  All-NBA Team  ROY  Success  \
89                    1          0             0    1        2
94                    0          0             0    1        1
182                   0          0             0    1        1
229                   1          0             0    0        1
308                   0          0             0    1        1

     Success Category  Season
89       high success  2023.0
94        low success  2022.0
182       low success  2021.0
229       low success  2021.0
308       low success  2020.0

[5 rows x 22 columns]
            Player   Age   G      MP    FG%    3P%    FT%  PER GAME MP  \
550    Luka Doncic  19.0  72  2318.0  0.427  0.327  0.713         32.2
857   Nikola Jokic  20.0  80  1733.0  0.512  0.333  0.811         21.7
1743  LeBron James  19.0  79  3122.0  0.417  0.290  0.754         39.5

      PER GAME  PTS  PER GAME TRB  ...  PER GAME BLK  PER GAME TOV  MVP  \
550            21.2           7.8  ...           0.3           3.4    0
857            10.0           7.0  ...           0.6           1.3    1
1743           20.9           5.5  ...           0.7           3.5    1

      All-Defensive Team  Final MVP  All-NBA Team  ROY  Success  \
550                    0          0             1    1        2
857                    0          1             0    0        2
1743                   1          1             1    1        5

      Success Category  Season
550       high success  2018.0
857       high success  2015.0
1743      high success  2003.0

[3 rows x 22 columns]

In [116]:
# Add a new column 'High Success': 1 if 'Success Category' is 'high success', 0 otherwise
filtered_dataset["High Success"] = filtered_dataset["Success Category"].apply(lambda x: 1 if x == "high success" else 0)

# Show a preview of the updated dataset
print(filtered_dataset.head())
print(filtered_dataset[filtered_dataset["Player"].isin(["LeBron James", "Nikola Jokic", "Luka Doncic"])])

                Player   Age   G      MP    FG%    3P%    FT%  PER GAME MP  \
89   Victor Wembanyama  20.0  52  1481.0  0.467  0.318  0.813         28.5
94      Paolo Banchero  20.0  72  2430.0  0.427  0.298  0.738         33.8
182     Scottie Barnes  20.0  74  2617.0  0.492  0.301  0.735         35.4
229      Herbert Jones  23.0  78  2335.0  0.476  0.337  0.840         29.9
308        LaMelo Ball  19.0  51  1469.0  0.436  0.352  0.758         28.8

     PER GAME  PTS  PER GAME TRB  ...  PER GAME TOV  MVP  All-Defensive Team  \
89            20.7          10.1  ...           3.4    0                   1
94            20.0           6.9  ...           2.8    0                   0
182           15.3           7.5  ...           1.8    0                   0
229            9.5           3.8  ...           1.3    0                   1
308           15.7           5.9  ...           2.8    0                   0

     Final MVP  All-NBA Team  ROY  Success  Success Category  Season  \
89           0             0    1        2      high success  2023.0
94           0             0    1        1       low success  2022.0
182          0             0    1        1       low success  2021.0
229          0             0    0        1       low success  2021.0
308          0             0    1        1       low success  2020.0

     High Success
89              1
94              0
182             0
229             0
308             0

[5 rows x 23 columns]
            Player   Age   G      MP    FG%    3P%    FT%  PER GAME MP  \
550    Luka Doncic  19.0  72  2318.0  0.427  0.327  0.713         32.2
857   Nikola Jokic  20.0  80  1733.0  0.512  0.333  0.811         21.7
1743  LeBron James  19.0  79  3122.0  0.417  0.290  0.754         39.5

      PER GAME  PTS  PER GAME TRB  ...  PER GAME TOV  MVP  All-Defensive Team  \
550            21.2           7.8  ...           3.4    0                   0
857            10.0           7.0  ...           1.3    1                   0
1743           20.9           5.5  ...           3.5    1                   1

      Final MVP  All-NBA Team  ROY  Success  Success Category  Season  \
550           0             1    1        2      high success  2018.0
857           1             0    0        2      high success  2015.0
1743          1             1    1        5      high success  2003.0

      High Success
550              1
857              1
1743             1

[3 rows x 23 columns]